error_log /var/www/localhost/htdocs/writable/logs/error.log;
access_log /var/www/localhost/htdocs/writable/logs/access.log;

gzip on;
gzip_comp_level 9;
gzip_min_length 256;
gzip_types text/plain text/css text/xml application/javascript application/json image/svg+xml;

server {
        listen 80;

        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl;

        ssl_certificate /etc/ssl/certs/localhost.crt;
        ssl_certificate_key /etc/ssl/private/localhost.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        root /var/www/localhost/htdocs/sub/public;

        index index.php;

        location / {
                try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
                fastcgi_pass  127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                include fastcgi_params;
        }
}
